name: recall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_ai: ^3.8.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  firebase_messaging: ^16.1.1
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  firebase_app_check: ^0.4.1+4
  get_it: ^9.2.0
  lottie: ^3.3.2
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  firebase_storage: ^13.0.6
  http: ^1.6.0
  flutter_svg: ^2.2.3
  internet_connection_checker_plus: ^2.9.1+2
  responsive_framework: ^1.5.1
  flutter_card_swiper: ^7.2.0
  responsive_scaler: ^1.0.1
  drift: ^2.31.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_gemma: ^0.12.4
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.3.2
  fluttertoast: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_timezone: ^5.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/svg/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk.ttf
      
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 26