name: recall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_ai: ^3.7.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  firebase_messaging: ^16.1.1
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  get_it: ^9.2.0
  lottie: ^3.3.2
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  http: ^1.6.0
  flutter_svg: ^2.2.3
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/svg/
    - assets/images/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk.ttf
      
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack.ttf
